travis:
  secure:
    BINSTAR_TOKEN: sb+8jSYSFk8osXwozYSV4FqE22evm6E/zBhHJn1L4L1o1GSEyvxSxcWE+efxnFM9QLA7wsfhPXyQevyDbhG/yXsbB5SKckxDBjwqs/i+TzETHXqscdVca6HTdn48O56B1Rm27S/HbhezxBNKP4NnkKjyjjy214uGl0oSON56+3/KEVzILdNUIGrPZXJ8Q4o4emFBmTgi2USV/rSnBUInMoUb3I24z60JmgXhoiARlGHkciFgzCimXFf53/cTNdfnXNP8ScwR0DLUupL46JV8WsK5htSI/OcRpR17YNV9uOa52THpTPH9LGHmBY6m84FZuwqDRpAWDB7FMjhBMvn8h9224d2ipfWa+QmfTIRThLSzb5UN+pJxATzSl9/w6/h2xjPg27ZsWtB6wEiIz8rWM6wrxssPSEQCiKPL6brHPfrCa3o3jy9JlbMYg5te7upCQXl6hbIfLjDHFPNq360mncRl3Jp421UFIPkIRel9Z0Ssqz3pe/hX9RpcLB35OnDlw+iU1dDN1ku6Iex9odTs7J/NzzhypX6xZvVc/QKujbnOkfYF3ZLLefSQZ3veLjz0a5//8T7pRqMPzWI+dXbDg7965onSjm01BMOV0VV/h4Lk8XtTpu0x3oRuOftNqV68RWFPcUOOm/QfN1iFjO0J7jCng4/SD4gAWPsYhaz9O2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
