travis:
  secure:
    BINSTAR_TOKEN: sAJDQggnaiZ4TV4fig+YwJYZEAZel1Czf+KULCrrJf0b1yePGPJPEcradQPB/YmOYol4HJyak3VK81F0UQZo/ltUDmTPYF+JucBeNqr2b86Es7feG03e4hqzMGvqyU4ZN9ycHxjdQc/pxTz1QS/ZDe8n7hGCpwlr7uvE/hTlBgJG4qZ5t8jLpOC0pxSF27uw/6mf43zhi598K7HK7SXhsNaIpaqvTDval9EsfmBLJDrcVAXi6RotDzG1BuIbRfqtipU2VL5gGe2KqTEwkahvbjsQtYFBb9xGxXzOzqvFM0tRTwzQC9dloCtjKL4PmFj8mA6xr5OQZ9/X5RKHcvZ6dl+u/k6j+VJuUPWMSzlPczEttRMGJg1XvgHydj0IOzGg0+cqHUHCjZHe50xGMZTR2kayLa+m/S0qWrTq5TMtW0Xa87ceBAU0XXd1f7mMpL42Vsw3gUigNH3EFk2cM5AhvfwmAzKSc3lpzC0RivIkyWuMnbrgEjsy6MMtEARP7JmlrxJKN1DbImmKi5BDQmcuoN/iQ6DrMbBLJQeF/0ouixrirnSCcZDhC2jrfFGeKVOwVSutf+2RnIRv2Ux4X9m7c/hkOGWnrxyU2B3zdOyio9xnCYM5gOC8iubI6L3jUizy9Bq3FWlBZCRxYtBfN+uHkQfNYdtyCZbuzDnljmLW2iQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
